name: Frist Workflow

on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Testing github actions first time"
      - name: Print goodbye
        run: echo "Done - bye!"
